---
excludes:
  scopes:
    - pattern: "dev"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for development only."
    - pattern: "lint"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for static code analysis only."
    - pattern: "test"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Packages for testing only."
license_choices:
  repository_license_choices:
    - given: FTL OR GPL-2.0-or-later
      choice: FTL
resolutions:
  rule_violations:
    - message: ".*PyPI::numpy:1\\.26\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause license: https://github.com/numpy/numpy/blob/v1.26.0/LICENSES_bundled.txt"
    - message: ".*PyPI::tiktoken:0\\.7\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/openai/tiktoken/blob/0.7.0/LICENSE"
    - message: ".*PyPI::httpcore:0\\.18\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause New or Revised License: https://github.com/encode/httpcore/blob/0.18.0/LICENSE.md"
    - message: ".*PyPI::httpx:0\\.25\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause New or Revised License: https://github.com/encode/httpx/blob/0.25.0/LICENSE.md"