[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
name = "aidial-adapter-openai"
version = "0.39.0rc"
description = "DIAL adapter for OpenAI"
authors = [{ name = "EPAM RAIL", email = "SpecialEPM-DIALDevTeam@epam.com" }]
license = "Apache-2.0"
readme = "README.md"
keywords = ["ai"]
classifiers = ["Topic :: Software Development :: Libraries :: Python Modules"]
requires-python = ">=3.11,<3.13"
dynamic = ["dependencies"]

[project.urls]
Homepage = "https://dialx.ai/"
Documentation = "https://dialx.ai/dial_api"
Repository = "https://github.com/epam/ai-dial-adapter-openai"

[project.scripts]
clean = "scripts.clean:main"

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
fastapi = "0.120.2"
openai = "2.16.0"
tiktoken = "0.12.0"
uvicorn = "0.23.0"
wrapt = "1.15.0"
pydantic = "2.10.4"
httpx = "0.27.0"
# required by openai embeddings; avoiding openai[datalib],
# since it also depends on pandas
numpy = "2.3.3"
pillow = "12.2.0"
azure-identity = "1.16.1"
# The default async transport in `azure-identity` is `aiohttp`
aiohttp = "3.13.4"
aidial-sdk = { version = "0.32.0", extras = ["telemetry"] }

[tool.poetry.group.test.dependencies]
pytest = "9.0.3"
pytest-asyncio = "1.3.0"
pytest-xdist = "^3.5.0"
respx = "^0.21.1"
pytest-timeout = "^2.4.0"
pytest-sugar = "^1.0.0"
pytest-env = "1.1.1"
rapidfuzz = "^3.14.1"
asgi-lifespan = "2.1.0"

[tool.poetry.group.lint.dependencies]
pyright = "1.1.408"
ruff = "0.12.11"

[tool.poetry.group.dev.dependencies]
nox = "^2023.4.22"
pre-commit = "^4.5.1"
# Required for `make serve` which loads .env file
python-dotenv = "^1.0.1"

[tool.pytest.ini_options]
addopts = "-n=auto --asyncio-mode=auto --timeout=300"
env = ["PYDANTIC_V2=1"]
testpaths = ["tests"]
filterwarnings = [
  "error",
  # muting warnings coming from opentelemetry and pkg_resources packages
  "ignore::DeprecationWarning:opentelemetry.instrumentation.dependencies",
  "ignore::DeprecationWarning:pkg_resources",
  # Workaround for this bug: https://github.com/openai/openai-python/issues/1039
  "ignore:Pydantic serializer warnings:UserWarning:pydantic.*",
]

[tool.pyright]
typeCheckingMode = "basic"
reportUnusedVariable = "error"
reportIncompatibleMethodOverride = "error"

[tool.ruff]
target-version = "py311"
line-length = 80

[tool.ruff.lint]
select = [
  "ERA",  # flake8-eradicate
  "B",    # flake8-builtins
  "C4",   # flake8-comprehensions
  "SIM",  # flake8-simplify
  "B9",   # flake8-bugbear
  "E",    # pycodestyle
  "W",    # pycodestyle
  "F",    # pyflakes
  "I",    # flake8-isort
  "S",    # flake8-bandit
  "FURB", # refurb
]
ignore = [
  "E501", # string literal is too long
  "E203", # whitespace before ':' (triggered on list slices like xs[i : i + 5])
  "S101", # Use of `assert` detected
  "S110", # `try`-`except`-`pass` detected
  "B904", # Within an `except` clause, raise exceptions with `raise ... from err` or `raise ... from None`
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
  "B011", # Do not `assert False`
  "B006", # Do not use mutable data structures for argument defaults
  "E731", # Do not assign a `lambda` expression, use a `def`
]
"*/__init__.py" = [
  "F401", # imported but unused
]
