[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
name = "aidial-adapter-openai"
version = "0.30.2"
description = "DIAL adapter for OpenAI"
authors = [{ name = "EPAM RAIL", email = "SpecialEPM-DIALDevTeam@epam.com" }]
license = "Apache-2.0"
readme = "README.md"
keywords = ["ai"]
classifiers = ["Topic :: Software Development :: Libraries :: Python Modules"]
requires-python = ">=3.11,<3.13"
dynamic = ["dependencies"]

[project.urls]
Homepage = "https://epam-rail.com"
Documentation = "https://epam-rail.com/dial_api"
Repository = "https://github.com/epam/ai-dial-adapter-openai"

[project.scripts]
clean = "scripts.clean:main"

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
fastapi = "0.116.1"
openai = "1.90.0"
tiktoken = "0.9.0"
uvicorn = "0.23.0"
wrapt = "1.15.0"
pydantic = "1.10.17"
httpx = "0.27.0"
# required by openai embeddings; avoiding openai[datalib],
# since it also depends on pandas
numpy = "1.26.0"
pillow = "10.3.0"
azure-identity = "1.16.1"
# The default async transport in `azure-identity` is `aiohttp`
aiohttp = "3.12.14"
aidial-sdk = { version = "0.22.1", extras = ["telemetry"] }

[tool.poetry.group.test.dependencies]
pytest = "7.4.0"
pytest-asyncio = "0.21.1"
pytest-xdist = "^3.5.0"
respx = "^0.21.1"
pytest-timeout = "^2.4.0"
pytest-sugar = "^1.0.0"

[tool.poetry.group.lint.dependencies]
pyright = "1.1.324"
black = "24.3.0"
isort = "5.12.0"
autoflake = "2.2.0"
flake8 = "6.0.0"

[tool.poetry.group.dev.dependencies]
nox = "^2023.4.22"
# Required for `make serve` which loads .env file
python-dotenv = "^1.0.1"

[tool.pytest.ini_options]
addopts = "-n=auto --asyncio-mode=auto --timeout=60"
testpaths = ["tests"]
filterwarnings = [
  "error",
  # thrown because of `get_http_client` isn't properly disposed between tests
  "ignore::pytest.PytestUnraisableExceptionWarning",
  # muting warnings coming from opentelemetry and pkg_resources packages
  "ignore::DeprecationWarning:opentelemetry.instrumentation.dependencies",
  "ignore::DeprecationWarning:pkg_resources",
]

[tool.pyright]
typeCheckingMode = "basic"
reportUnusedVariable = "error"
reportIncompatibleMethodOverride = "error"
exclude = [".git", ".venv", ".nox", "**/__pycache__"]

[tool.black]
line-length = 80
exclude = '''
/(
    \.git
  | \.venv
  | \.nox
  | \.__pycache__
)/
'''

[tool.isort]
line_length = 80
profile = "black"

[tool.autoflake]
ignore_init_module_imports = true
remove_all_unused_imports = true
in_place = true
recursive = true
quiet = true
exclude = ["\\.venv", "\\.nox"]
