from enum import StrEnum


class ChatCompletionDeploymentType(StrEnum):
    GPT_IMAGE_1 = "GPT_IMAGE_1"
    DALLE3 = "DALLE3"
    MISTRAL = "MISTRAL"
    DATABRICKS = "DATABRICKS"
    GPT4O = "GPT4O"
    GPT4O_MINI = "GPT4O_MINI"
    GPT_GENERIC = "GPT_GENERIC"
    VLLM_CHAT_COMPLETIONS_API = "VLLM_CHAT_COMPLETIONS_API"
    QWEN3_ASR_VLLM_CHAT_COMPLETIONS_API = "QWEN3_ASR_VLLM_CHAT_COMPLETIONS_API"
    RESPONSES_API = "RESPONSES_API"
    COMPLETIONS_API = "COMPLETIONS_API"
    AZURE_VIDEO_API = "AZURE_VIDEO_API"
    OPENAI_VIDEO_API = "OPENAI_VIDEO_API"
    AUDIO_SPEECH_API = "SPEECH_API"
    AUDIO_TRANSCRIPTIONS_API = "TRANSCRIPTIONS_API"
    ANTHROPIC_MESSAGES_API = "ANTHROPIC_MESSAGES_API"
