from enum import StrEnum


class ChatCompletionDeploymentType(StrEnum):
    GPT_IMAGE_1 = "GPT_IMAGE_1"
    DALLE3 = "DALLE3"
    MISTRAL = "MISTRAL"
    DATABRICKS = "DATABRICKS"
    GPT4O = "GPT4O"
    GPT4O_MINI = "GPT4O_MINI"
    GPT_GENERIC = "GPT_GENERIC"
    VLLM = "VLLM"
    RESPONSES_API = "RESPONSES_API"
    COMPLETIONS_API = "COMPLETIONS_API"
    AZURE_VIDEO_API = "AZURE_VIDEO_API"
    OPENAI_VIDEO_API = "OPENAI_VIDEO_API"
    AUDIO_SPEECH_API = "SPEECH_API"
    AUDIO_TRANSCRIPTIONS_API = "TRANSCRIPTIONS_API"
