name: PR Workflow

on:
  pull_request:
    branches: [development, release-*]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  run_tests:
    uses: epam/ai-dial-ci/.github/workflows/python_docker_pr.yml@4.8.0
    secrets: inherit
    with:
      python-version: "3.11"
      poetry-version: "2.1.1"
      platforms: "linux/amd64,linux/arm64"
