name: Release Workflow

on:
  workflow_dispatch:
  push:
    branches: [development, release-*]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: epam/ai-dial-ci/.github/workflows/python_docker_release.yml@3.2.0
    secrets: inherit
    with:
      python-version: "3.11"
      poetry-version: "2.1.1"
      platforms: "linux/amd64,linux/arm64"
